const DamageFormulaType = Object.freeze({
	NO_DAMAGE: Symbol("noDamage"),
	NON_STANDARD_DAMAGE: Symbol("nonStandardDamage"),
	STANDARD_DAMAGE: Symbol("standardDamage"),
})

const moves = {
	"Pound"         : { name: "Pound",         battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Karate Chop"   : { name: "Karate Chop",   battleEffect: "HighCritical",                type: "Fighting" , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"DoubleSlap"    : { name: "DoubleSlap",    battleEffect: "MultiHit",                    type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Comet Punch"   : { name: "Comet Punch",   battleEffect: "MultiHit",                    type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Mega Punch"    : { name: "Mega Punch",    battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Pay Day"       : { name: "Pay Day",       battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Fire Punch"    : { name: "Fire Punch",    battleEffect:  null,                         type: "Fire"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Ice Punch"     : { name: "Ice Punch",     battleEffect:  null,                         type: "Ice"      , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"ThunderPunch"  : { name: "ThunderPunch",  battleEffect:  null,                         type: "Electric" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Scratch"       : { name: "Scratch",       battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"ViceGrip"      : { name: "ViceGrip",      battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Guillotine"    : { name: "Guillotine",    battleEffect: "Ohko",                        type:  null      , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Razor Wind"    : { name: "Razor Wind",    battleEffect: "RazorWind",                   type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     },
	"Swords Dance"  : { name: "Swords Dance",  battleEffect: "UserAttackUp2",               type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Cut"           : { name: "Cut",           battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Gust"          : { name: "Gust",          battleEffect:  null,                         type: "Flying"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Wing Attack"   : { name: "Wing Attack",   battleEffect:  null,                         type: "Flying"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Whirlwind"     : { name: "Whirlwind",     battleEffect: "ForceSwitch",                 type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Fly"           : { name: "Fly",           battleEffect: "Fly",                         type: "Flying"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Bind"          : { name: "Bind",          battleEffect: "Trap",                        type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Slam"          : { name: "Slam",          battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Vine Whip"     : { name: "Vine Whip",     battleEffect:  null,                         type: "Grass"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Stomp"         : { name: "Stomp",         battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Double Kick"   : { name: "Double Kick",   battleEffect: "MultiHit",                   type: "Fighting" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Mega Kick"     : { name: "Mega Kick",     battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Jump Kick"     : { name: "Jump Kick",     battleEffect:  null,                         type: "Fighting" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Rolling Kick"  : { name: "Rolling Kick",  battleEffect:  null,                         type: "Fighting" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Sand-Attack"   : { name: "Sand-Attack",   battleEffect: "TargetAccuracyDown1",         type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Headbutt"      : { name: "Headbutt",      battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Horn Attack"   : { name: "Horn Attack",   battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Fury Attack"   : { name: "Fury Attack",   battleEffect: "MultiHit",                    type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Horn Drill"    : { name: "Horn Drill",    battleEffect: "Ohko",                        type: "Normal"   , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Tackle"        : { name: "Tackle",        battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Body Slam"     : { name: "Body Slam",     battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Wrap"          : { name: "Wrap",          battleEffect: "Trap",                        type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Take Down"     : { name: "Take Down",     battleEffect: "14Recoil",                    type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Thrash"        : { name: "Thrash",        battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Double-Edge"   : { name: "Double-Edge",   battleEffect: "13Recoil",                    type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Tail Whip"     : { name: "Tail Whip",     battleEffect: "TargetDefenseDown1",          type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Poison Sting"  : { name: "Poison Sting",  battleEffect:  null,                         type: "Poison"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Twineedle"     : { name: "Twineedle",     battleEffect: "MultiHit",                    type: "Bug"      , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Pin Missile"   : { name: "Pin Missile",   battleEffect: "MultiHit",                    type: "Bug"      , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Leer"          : { name: "Leer",          battleEffect: "TargetDefenseDown1",          type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Bite"          : { name: "Bite",          battleEffect:  null,                         type: "Dark"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Growl"         : { name: "Growl",         battleEffect: "TargetAttackDown1",           type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Roar"          : { name: "Roar",          battleEffect: "ForceSwitch",                 type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Sing"          : { name: "Sing",          battleEffect: "InflictSleep",                type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Supersonic"    : { name: "Supersonic",    battleEffect: "InflictConfusion",            type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"SonicBoom"     : { name: "SonicBoom",     battleEffect: "Sonicboom",                   type: "Normal"   , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Disable"       : { name: "Disable",       battleEffect: "Disable",                     type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Acid"          : { name: "Acid",          battleEffect:  null,                         type: "Poison"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Ember"         : { name: "Ember",         battleEffect:  null,                         type: "Fire"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Flamethrower"  : { name: "Flamethrower",  battleEffect:  null,                         type: "Fire"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Mist"          : { name: "Mist",          battleEffect: "Mist",                        type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Water Gun"     : { name: "Water Gun",     battleEffect:  null,                         type: "Water"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Hydro Pump"    : { name: "Hydro Pump",    battleEffect:  null,                         type: "Water"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Surf"          : { name: "Surf",          battleEffect:  null,                         type: "Water"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Ice Beam"      : { name: "Ice Beam",      battleEffect:  null,                         type: "Ice"      , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Blizzard"      : { name: "Blizzard",      battleEffect:  null,                         type: "Ice"      , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Psybeam"       : { name: "Psybeam",       battleEffect:  null,                         type: "Psychic"  , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"BubbleBeam"    : { name: "BubbleBeam",    battleEffect: "DamageAndTargetSpeedDown1",   type: "Water"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Aurora Beam"   : { name: "Aurora Beam",   battleEffect:  null,                         type: "Ice"      , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Hyper Beam"    : { name: "Hyper Beam",    battleEffect: "MustRecharge",                type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Peck"          : { name: "Peck",          battleEffect:  null,                         type: "Flying"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Drill Peck"    : { name: "Drill Peck",    battleEffect:  null,                         type: "Flying"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Submission"    : { name: "Submission",    battleEffect: "14Recoil",                    type: "Fighting" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Low Kick"      : { name: "Low Kick",      battleEffect: "DamageByTargetWeight",        type: "Fighting" , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Counter"       : { name: "Counter",       battleEffect: "Counter",                     type:  null      , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Seismic Toss"  : { name: "Seismic Toss",  battleEffect: "DamageIsLevel",               type: "Fighting" , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Strength"      : { name: "Strength",      battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Absorb"        : { name: "Absorb",        battleEffect: "HpDrain",                     type: "Grass"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Mega Drain"    : { name: "Mega Drain",    battleEffect: "HpDrain",                     type: "Grass"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Leech Seed"    : { name: "Leech Seed",    battleEffect: "LeechSeed",                   type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Growth"        : { name: "Growth",        battleEffect: "UserSpattackUp1",             type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Razor Leaf"    : { name: "Razor Leaf",    battleEffect: "HighCritical",                type: "Grass"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"SolarBeam"     : { name: "SolarBeam",     battleEffect: "Solarbeam",                   type: "Grass"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"PoisonPowder"  : { name: "PoisonPowder",  battleEffect: "InflictPoison",               type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Stun Spore"    : { name: "Stun Spore",    battleEffect: "InflictParalysis",            type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Sleep Powder"  : { name: "Sleep Powder",  battleEffect: "InflictSleep",                type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Petal Dance"   : { name: "Petal Dance",   battleEffect:  null,                         type: "Grass"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"String Shot"   : { name: "String Shot",   battleEffect: "TargetSpeedDown1",            type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Dragon Rage"   : { name: "Dragon Rage",   battleEffect: "DragonRage",                  type:  null      , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Fire Spin"     : { name: "Fire Spin",     battleEffect: "Trap",                        type: "Fire"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"ThunderShock"  : { name: "ThunderShock",  battleEffect:  null,                         type: "Electric" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Thunderbolt"   : { name: "Thunderbolt",   battleEffect:  null,                         type: "Electric" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Thunder Wave"  : { name: "Thunder Wave",  battleEffect: "InflictParalysis",            type: "Electric" , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Thunder"       : { name: "Thunder",       battleEffect:  null,                         type: "Electric" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Rock Throw"    : { name: "Rock Throw",    battleEffect:  null,                         type: "Rock"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Earthquake"    : { name: "Earthquake",    battleEffect:  null,                         type: "Ground"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Fissure"       : { name: "Fissure",       battleEffect: "Ohko",                        type: "Ground"   , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Dig"           : { name: "Dig",           battleEffect: "Dig",                         type: "Ground"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Toxic"         : { name: "Toxic",         battleEffect: "Toxic",                       type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Confusion"     : { name: "Confusion",     battleEffect:  null,                         type: "Psychic"  , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Psychic"       : { name: "Psychic",       battleEffect:  null,                         type: "Psychic"  , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Hypnosis"      : { name: "Hypnosis",      battleEffect: "InflictSleep",                type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Meditate"      : { name: "Meditate",      battleEffect: "UserAttackUp1",               type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Agility"       : { name: "Agility",       battleEffect: "UserSpeedUp2",                type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Quick Attack"  : { name: "Quick Attack",  battleEffect: "Priority",                    type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Rage"          : { name: "Rage",          battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Teleport"      : { name: "Teleport",      battleEffect: "Teleport",                    type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Night Shade"   : { name: "Night Shade",   battleEffect: "DamageIsLevel",               type: "Ghost"    , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Mimic"         : { name: "Mimic",         battleEffect: "Mimic",                       type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Screech"       : { name: "Screech",       battleEffect: "TargetDefenseDown2",          type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Double Team"   : { name: "Double Team",   battleEffect: "UserEvasionUp1",              type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Recover"       : { name: "Recover",       battleEffect: "Recover",                     type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Harden"        : { name: "Harden",        battleEffect: "UserDefenseUp1",              type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Minimize"      : { name: "Minimize",      battleEffect: "Minimize",                    type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"SmokeScreen"   : { name: "SmokeScreen",   battleEffect: "TargetAccuracyDown1",         type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Confuse Ray"   : { name: "Confuse Ray",   battleEffect: "InflictConfusion",            type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Withdraw"      : { name: "Withdraw",      battleEffect: "UserDefenseUp1",              type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Defense Curl"  : { name: "Defense Curl",  battleEffect: "DefenseCurl",                 type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Barrier"       : { name: "Barrier",       battleEffect: "UserDefenseUp2",              type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Light Screen"  : { name: "Light Screen",  battleEffect: "LightScreen",                 type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Haze"          : { name: "Haze",          battleEffect: "Haze",                        type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Reflect"       : { name: "Reflect",       battleEffect: "Reflect",                     type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Focus Energy"  : { name: "Focus Energy",  battleEffect: "FocusEnergy",                 type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Bide"          : { name: "Bide",          battleEffect: "Bide",                        type:  null      , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Metronome"     : { name: "Metronome",     battleEffect: "Metronome",                   type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Mirror Move"   : { name: "Mirror Move",   battleEffect: "MirrorMove",                  type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Selfdestruct"  : { name: "Selfdestruct",  battleEffect: "Selfdestruction",             type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Egg Bomb"      : { name: "Egg Bomb",      battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Lick"          : { name: "Lick",          battleEffect:  null,                         type: "Ghost"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Smog"          : { name: "Smog",          battleEffect:  null,                         type: "Poison"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Sludge"        : { name: "Sludge",        battleEffect:  null,                         type: "Poison"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Bone Club"     : { name: "Bone Club",     battleEffect:  null,                         type: "Ground"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Fire Blast"    : { name: "Fire Blast",    battleEffect:  null,                         type: "Fire"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Waterfall"     : { name: "Waterfall",     battleEffect:  null,                         type: "Water"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Clamp"         : { name: "Clamp",         battleEffect: "Trap",                        type: "Water"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Swift"         : { name: "Swift",         battleEffect: "CannotMiss",                  type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Skull Bash"    : { name: "Skull Bash",    battleEffect: "SkullBash",                   type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Spike Cannon"  : { name: "Spike Cannon",  battleEffect: "MultiHit",                    type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Constrict"     : { name: "Constrict",     battleEffect: "DamageAndTargetSpeedDown1",   type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Amnesia"       : { name: "Amnesia",       battleEffect: "UserSpdefenseUp2",            type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Kinesis"       : { name: "Kinesis",       battleEffect: "TargetAccuracyDown1",         type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Softboiled"    : { name: "Softboiled",    battleEffect: "Recover",                     type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Hi Jump Kick"  : { name: "Hi Jump Kick",  battleEffect:  null,                         type: "Fighting" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Glare"         : { name: "Glare",         battleEffect: "InflictParalysis",            type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Dream Eater"   : { name: "Dream Eater",   battleEffect: "DreamEater",                  type: "Psychic"  , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Poison Gas"    : { name: "Poison Gas",    battleEffect: "InflictPoison",               type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Barrage"       : { name: "Barrage",       battleEffect: "MultiHit",                    type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Leech Life"    : { name: "Leech Life",    battleEffect: "HpDrain",                     type: "Bug"      , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Lovely Kiss"   : { name: "Lovely Kiss",   battleEffect: "InflictSleep",                type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Sky Attack"    : { name: "Sky Attack",    battleEffect: "SkyAttack",                   type: "Flying"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Transform"     : { name: "Transform",     battleEffect: "Transform",                   type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Bubble"        : { name: "Bubble",        battleEffect: "DamageAndTargetSpeedDown1",   type: "Water"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Dizzy Punch"   : { name: "Dizzy Punch",   battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Spore"         : { name: "Spore",         battleEffect: "InflictSleep",                type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Flash"         : { name: "Flash",         battleEffect: "TargetAccuracyDown1",         type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Psywave"       : { name: "Psywave",       battleEffect: "Psywave",                     type: "Psychic"  , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Splash"        : { name: "Splash",        battleEffect: "NoDamage",                    type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Acid Armor"    : { name: "Acid Armor",    battleEffect: "UserDefenseUp2",              type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Crabhammer"    : { name: "Crabhammer",    battleEffect: "HighCritical",                type: "Water"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Explosion"     : { name: "Explosion",     battleEffect: "Selfdestruction",             type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Fury Swipes"   : { name: "Fury Swipes",   battleEffect: "MultiHit",                    type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Bonemerang"    : { name: "Bonemerang",    battleEffect: "MultiHit",                    type: "Ground"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Rest"          : { name: "Rest",          battleEffect: "Rest",                        type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Rock Slide"    : { name: "Rock Slide",    battleEffect:  null,                         type: "Rock"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Hyper Fang"    : { name: "Hyper Fang",    battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Sharpen"       : { name: "Sharpen",       battleEffect: "UserAttackUp1",               type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Conversion"    : { name: "Conversion",    battleEffect: "Conversion",                  type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Tri Attack"    : { name: "Tri Attack",    battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Super Fang"    : { name: "Super Fang",    battleEffect: "SuperFang",                   type:  null      , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Slash"         : { name: "Slash",         battleEffect: "HighCritical",                type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Substitute"    : { name: "Substitute",    battleEffect: "Substitute",                  type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
//	"Struggle"      : { name: "Struggle",      battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Sketch"        : { name: "Sketch",        battleEffect: "Sketch",                      type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Triple Kick"   : { name: "Triple Kick",   battleEffect:  null,                         type: "Fighting" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Thief"         : { name: "Thief",         battleEffect: "StealItem",                   type: "Dark"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Spider Web"    : { name: "Spider Web",    battleEffect: "BlockEscape",                 type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Mind Reader"   : { name: "Mind Reader",   battleEffect: "LockOn",                      type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Nightmare"     : { name: "Nightmare",     battleEffect: "Nightmare",                   type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Flame Wheel"   : { name: "Flame Wheel",   battleEffect:  null,                         type: "Fire"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Snore"         : { name: "Snore",         battleEffect: "Snore",                       type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Curse"         : { name: "Curse",         battleEffect: "Curse",                       type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Flail"         : { name: "Flail",         battleEffect: "LowHpHighDamage",             type:  null      , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Conversion2"   : { name: "Conversion2",   battleEffect: "Conversion2",                 type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Aeroblast"     : { name: "Aeroblast",     battleEffect: "HighCritical",                type: "Flying"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Cotton Spore"  : { name: "Cotton Spore",  battleEffect: "TargetSpeedDown2",            type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Reversal"      : { name: "Reversal",      battleEffect: "LowHpHighDamage",             type:  null      , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Spite"         : { name: "Spite",         battleEffect: "Spite",                       type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Powder Snow"   : { name: "Powder Snow",   battleEffect:  null,                         type: "Ice"      , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Protect"       : { name: "Protect",       battleEffect: "Protect",                     type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Mach Punch"    : { name: "Mach Punch",    battleEffect: "Priority",                    type: "Fighting" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Scary Face"    : { name: "Scary Face",    battleEffect: "TargetSpeedDown2",            type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Faint Attack"  : { name: "Faint Attack",  battleEffect: "CannotMiss",                  type: "Dark"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Sweet Kiss"    : { name: "Sweet Kiss",    battleEffect: "InflictConfusion",            type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Belly Drum"    : { name: "Belly Drum",    battleEffect: "BellyDrum",                   type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Sludge Bomb"   : { name: "Sludge Bomb",   battleEffect:  null,                         type: "Poison"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Mud-Slap"      : { name: "Mud-Slap",      battleEffect:  null,                         type: "Ground"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Octazooka"     : { name: "Octazooka",     battleEffect:  null,                         type: "Water"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Spikes"        : { name: "Spikes",        battleEffect: "Spikes",                      type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Zap Cannon"    : { name: "Zap Cannon",    battleEffect:  null,                         type: "Electric" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Foresight"     : { name: "Foresight",     battleEffect: "Identify",                    type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Destiny Bond"  : { name: "Destiny Bond",  battleEffect: "DestinyBond",                 type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Perish Song"   : { name: "Perish Song",   battleEffect: "PerishSong",                  type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Icy Wind"      : { name: "Icy Wind",      battleEffect: "DamageAndTargetSpeedDown1",   type: "Ice"      , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Detect"        : { name: "Detect",        battleEffect: "Protect",                     type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Bone Rush"     : { name: "Bone Rush",     battleEffect: "MultiHit",                    type: "Ground"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Lock-On"       : { name: "Lock-On",       battleEffect: "LockOn",                      type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Outrage"       : { name: "Outrage",       battleEffect:  null,                         type: "Dragon"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Sandstorm"     : { name: "Sandstorm",     battleEffect: "Sandstorm",                   type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Giga Drain"    : { name: "Giga Drain",    battleEffect: "HpDrain",                     type: "Grass"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Endure"        : { name: "Endure",        battleEffect: "Endure",                      type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Charm"         : { name: "Charm",         battleEffect: "TargetAttackDown2",           type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Rollout"       : { name: "Rollout",       battleEffect:  null,                         type: "Rock"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"False Swipe"   : { name: "False Swipe",   battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Swagger"       : { name: "Swagger",       battleEffect: "Swagger",                     type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Milk Drink"    : { name: "Milk Drink",    battleEffect: "Recover",                     type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Spark"         : { name: "Spark",         battleEffect:  null,                         type: "Electric" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Fury Cutter"   : { name: "Fury Cutter",   battleEffect:  null,                         type: "Bug"      , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Steel Wing"    : { name: "Steel Wing",    battleEffect:  null,                         type: "Steel"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Mean Look"     : { name: "Mean Look",     battleEffect: "BlockEscape",                 type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Attract"       : { name: "Attract",       battleEffect: "Attract",                     type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Sleep Talk"    : { name: "Sleep Talk",    battleEffect: "SleepTalk",                   type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Heal Bell"     : { name: "Heal Bell",     battleEffect: "HealBell",                    type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Return"        : { name: "Return",        battleEffect: "Return",                      type: "Normal"   , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Present"       : { name: "Present",       battleEffect: "Present",                     type:  null      , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Frustration"   : { name: "Frustration",   battleEffect: "Frustration",                 type: "Normal"   , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Safeguard"     : { name: "Safeguard",     battleEffect: "Safeguard",                   type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Pain Split"    : { name: "Pain Split",    battleEffect: "PainSplit",                   type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Sacred Fire"   : { name: "Sacred Fire",   battleEffect:  null,                         type: "Fire"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Magnitude"     : { name: "Magnitude",     battleEffect: "Magnitude",                   type: "Ground"   , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"DynamicPunch"  : { name: "DynamicPunch",  battleEffect:  null,                         type: "Fighting" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Megahorn"      : { name: "Megahorn",      battleEffect:  null,                         type: "Bug"      , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"DragonBreath"  : { name: "DragonBreath",  battleEffect:  null,                         type: "Dragon"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Baton Pass"    : { name: "Baton Pass",    battleEffect: "BatonPass",                   type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Encore"        : { name: "Encore",        battleEffect: "Encore",                      type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Pursuit"       : { name: "Pursuit",       battleEffect: "Pursuit",                     type: "Dark"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Rapid Spin"    : { name: "Rapid Spin",    battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Sweet Scent"   : { name: "Sweet Scent",   battleEffect: "TargetEvasionDown1",          type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Iron Tail"     : { name: "Iron Tail",     battleEffect:  null,                         type: "Steel"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Metal Claw"    : { name: "Metal Claw",    battleEffect:  null,                         type: "Steel"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Vital Throw"   : { name: "Vital Throw",   battleEffect: "VitalThrow",                  type: "Fighting" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Morning Sun"   : { name: "Morning Sun",   battleEffect: "SunRecover",                  type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Synthesis"     : { name: "Synthesis",     battleEffect: "SunRecover",                  type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Moonlight"     : { name: "Moonlight",     battleEffect: "SunRecover",                  type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Hidden Power"  : { name: "Hidden Power",  battleEffect: "HiddenPower",                 type:  null      , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Cross Chop"    : { name: "Cross Chop",    battleEffect: "HighCritical",                type: "Fighting" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Twister"       : { name: "Twister",       battleEffect:  null,                         type: "Dragon"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Rain Dance"    : { name: "Rain Dance",    battleEffect: "RainDance",                   type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Sunny Day"     : { name: "Sunny Day",     battleEffect: "SunnyDay",                    type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Crunch"        : { name: "Crunch",        battleEffect:  null,                         type: "Dark"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Mirror Coat"   : { name: "Mirror Coat",   battleEffect: "MirrorCoat",                  type:  null      , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Psych Up"      : { name: "Psych Up",      battleEffect: "PsychUp",                     type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"ExtremeSpeed"  : { name: "ExtremeSpeed",  battleEffect: "Priority",                    type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"AncientPower"  : { name: "AncientPower",  battleEffect:  null,                         type: "Rock"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Shadow Ball"   : { name: "Shadow Ball",   battleEffect:  null,                         type: "Ghost"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Future Sight"  : { name: "Future Sight",  battleEffect: "FutureAttack",                type: "Psychic"  , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Rock Smash"    : { name: "Rock Smash",    battleEffect:  null,                         type: "Fighting" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Whirlpool"     : { name: "Whirlpool",     battleEffect:  "Trap",                       type: "Water"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Beat Up"       : { name: "Beat Up",       battleEffect:  null,                         type: "Dark"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Fake Out"      : { name: "Fake Out",      battleEffect: "FakeOut",                     type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Uproar"        : { name: "Uproar",        battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Stockpile"     : { name: "Stockpile",     battleEffect: "Stockpile",                   type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Spit Up"       : { name: "Spit Up",       battleEffect: "SpitUp",                      type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Swallow"       : { name: "Swallow",       battleEffect: "Swallow",                     type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Heat Wave"     : { name: "Heat Wave",     battleEffect:  null,                         type: "Fire"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Hail"          : { name: "Hail",          battleEffect: "Hail",                        type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Torment"       : { name: "Torment",       battleEffect: "Torment",                     type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Flatter"       : { name: "Flatter",       battleEffect: "Flatter",                     type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Will-O-Wisp"   : { name: "Will-O-Wisp",   battleEffect: "InflictBurn",                 type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Memento"       : { name: "Memento",       battleEffect: "Memento",                     type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Facade"        : { name: "Facade",        battleEffect: "Facade",                      type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Focus Punch"   : { name: "Focus Punch",   battleEffect: "FocusPunch",                  type: "Fighting" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"SmellingSalt"  : { name: "SmellingSalt",  battleEffect: "SmellingSalt",                type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Follow Me"     : { name: "Follow Me",     battleEffect: "FollowMe",                    type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Nature Power"  : { name: "Nature Power",  battleEffect: "NaturePower",                 type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Charge"        : { name: "Charge",        battleEffect: "Charge",                      type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Taunt"         : { name: "Taunt",         battleEffect: "Taunt",                       type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Helping Hand"  : { name: "Helping Hand",  battleEffect: "HelpingHand",                 type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Trick"         : { name: "Trick",         battleEffect: "SwitchItems",                 type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Role Play"     : { name: "Role Play",     battleEffect: "RolePlay",                    type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Wish"          : { name: "Wish",          battleEffect: "Wish",                        type:  null      , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Assist"        : { name: "Assist",        battleEffect: "Assist",                      type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Ingrain"       : { name: "Ingrain",       battleEffect: "Ingrain",                     type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Superpower"    : { name: "Superpower",    battleEffect: "Superpower",                  type: "Fighting" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Magic Coat"    : { name: "Magic Coat",    battleEffect: "MagicCoat",                   type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Recycle"       : { name: "Recycle",       battleEffect: "Recycle",                     type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Revenge"       : { name: "Revenge",       battleEffect: "DamageRevenge",               type: "Fighting" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Brick Break"   : { name: "Brick Break",   battleEffect: "BrickBreak",                  type: "Fighting" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Yawn"          : { name: "Yawn",          battleEffect: "Yawn",                        type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Knock Off"     : { name: "Knock Off",     battleEffect: "KnockOff",                    type: "Dark"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Endeavor"      : { name: "Endeavor",      battleEffect: "Endeavor",                    type:  null      , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Eruption"      : { name: "Eruption",      battleEffect: "HighHpHighDamage",            type: "Fire"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Skill Swap"    : { name: "Skill Swap",    battleEffect: "SkillSwap",                   type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Imprison"      : { name: "Imprison",      battleEffect: "Imprison",                    type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Refresh"       : { name: "Refresh",       battleEffect: "Refresh",                     type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Grudge"        : { name: "Grudge",        battleEffect: "Grudge",                      type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Snatch"        : { name: "Snatch",        battleEffect: "Snatch",                      type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Secret Power"  : { name: "Secret Power",  battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Dive"          : { name: "Dive",          battleEffect: "Dive",                        type: "Water"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Arm Thrust"    : { name: "Arm Thrust",    battleEffect: "MultiHit",                    type: "Fighting" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Camouflage"    : { name: "Camouflage",    battleEffect: "Camouflage",                  type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Tail Glow"     : { name: "Tail Glow",     battleEffect: "UserSpattackUp2",             type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Luster Purge"  : { name: "Luster Purge",  battleEffect:  null,                         type: "Psychic"  , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Mist Ball"     : { name: "Mist Ball",     battleEffect:  null,                         type: "Psychic"  , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"FeatherDance"  : { name: "FeatherDance",  battleEffect: "TargetAttackDown2",           type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Teeter Dance"  : { name: "Teeter Dance",  battleEffect: "TeeterDance",                 type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Blaze Kick"    : { name: "Blaze Kick",    battleEffect: "BlazeKick",                   type: "Fire"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Mud Sport"     : { name: "Mud Sport",     battleEffect: "MudSport",                    type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Ice Ball"      : { name: "Ice Ball",      battleEffect:  null,                         type: "Ice"      , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Needle Arm"    : { name: "Needle Arm",    battleEffect:  null,                         type: "Grass"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Slack Off"     : { name: "Slack Off",     battleEffect: "Recover",                     type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Hyper Voice"   : { name: "Hyper Voice",   battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Poison Fang"   : { name: "Poison Fang",   battleEffect:  null,                         type: "Poison"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Crush Claw"    : { name: "Crush Claw",    battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Blast Burn"    : { name: "Blast Burn",    battleEffect: "MustRecharge",                type: "Fire"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Hydro Cannon"  : { name: "Hydro Cannon",  battleEffect: "MustRecharge",                type: "Water"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Meteor Mash"   : { name: "Meteor Mash",   battleEffect:  null,                         type: "Steel"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Astonish"      : { name: "Astonish",      battleEffect:  null,                         type: "Ghost"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Weather Ball"  : { name: "Weather Ball",  battleEffect:  null,                         type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Aromatherapy"  : { name: "Aromatherapy",  battleEffect: "HealBell",                    type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Fake Tears"    : { name: "Fake Tears",    battleEffect: "TargetSpdefenseDown2",        type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Air Cutter"    : { name: "Air Cutter",    battleEffect: "HighCritical",                type: "Flying"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Overheat"      : { name: "Overheat",      battleEffect: "DamageAndUserSpattackDown2",  type: "Fire"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Odor Sleuth"   : { name: "Odor Sleuth",   battleEffect: "Identify",                    type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Rock Tomb"     : { name: "Rock Tomb",     battleEffect: "DamageAndTargetSpeedDown1",   type: "Rock"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     },
	"Silver Wind"   : { name: "Silver Wind",   battleEffect:  null,                         type: "Bug"      , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Metal Sound"   : { name: "Metal Sound",   battleEffect: "TargetSpdefenseDown2",        type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"GrassWhistle"  : { name: "GrassWhistle",  battleEffect: "InflictSleep",                type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Tickle"        : { name: "Tickle",        battleEffect: "Tickle",                      type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Cosmic Power"  : { name: "Cosmic Power",  battleEffect: "BothDefenseUp1",              type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Water Spout"   : { name: "Water Spout",   battleEffect: "HighHpHighDamage",            type: "Water"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Signal Beam"   : { name: "Signal Beam",   battleEffect:  null,                         type: "Bug"      , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Shadow Punch"  : { name: "Shadow Punch",  battleEffect: "CannotMiss",                  type: "Ghost"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Extrasensory"  : { name: "Extrasensory",  battleEffect:  null,                         type: "Psychic"  , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Sky Uppercut"  : { name: "Sky Uppercut",  battleEffect:  null,                         type: "Fighting" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Sand Tomb"     : { name: "Sand Tomb",     battleEffect: "Trap",                        type: "Ground"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Sheer Cold"    : { name: "Sheer Cold",    battleEffect: "Ohko",                        type:  null      , damageFormula: DamageFormulaType.NON_STANDARD_DAMAGE }, 
	"Muddy Water"   : { name: "Muddy Water",   battleEffect:  null,                         type: "Water"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Bullet Seed"   : { name: "Bullet Seed",   battleEffect: "MultiHit",                    type: "Grass"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Aerial Ace"    : { name: "Aerial Ace",    battleEffect: "CannotMiss",                  type: "Flying"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Icicle Spear"  : { name: "Icicle Spear",  battleEffect: "MultiHit",                    type: "Ice"      , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Iron Defense"  : { name: "Iron Defense",  battleEffect: "UserDefenseUp2",              type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Block"         : { name: "Block",         battleEffect: "BlockEscape",                 type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Howl"          : { name: "Howl",          battleEffect: "UserAttackUp1",               type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Dragon Claw"   : { name: "Dragon Claw",   battleEffect:  null,                         type: "Dragon"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Frenzy Plant"  : { name: "Frenzy Plant",  battleEffect: "MustRecharge",                type: "Grass"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Bulk Up"       : { name: "Bulk Up",       battleEffect: "BulkUp",                      type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Bounce"        : { name: "Bounce",        battleEffect: "Bounce",                      type: "Flying"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Mud Shot"      : { name: "Mud Shot",      battleEffect: "DamageAndTargetSpeedDown1",   type: "Ground"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     },
	"Poison Tail"   : { name: "Poison Tail",   battleEffect: "PoisonTail",                  type: "Poison"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Covet"         : { name: "Covet",         battleEffect: "StealItem",                   type: "Normal"   , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Volt Tackle"   : { name: "Volt Tackle",   battleEffect: "VoltTackle",                  type: "Electric" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Magical Leaf"  : { name: "Magical Leaf",  battleEffect: "CannotMiss",                  type: "Grass"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Water Sport"   : { name: "Water Sport",   battleEffect: "WaterSport",                  type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Calm Mind"     : { name: "Calm Mind",     battleEffect: "CalmMind",                    type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Leaf Blade"    : { name: "Leaf Blade",    battleEffect: "HighCritical",                type: "Grass"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Dragon Dance"  : { name: "Dragon Dance",  battleEffect: "DragonDance",                 type:  null      , damageFormula: DamageFormulaType.NO_DAMAGE           }, 
	"Rock Blast"    : { name: "Rock Blast",    battleEffect: "MultiHit",                    type: "Rock"     , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Shock Wave"    : { name: "Shock Wave",    battleEffect: "CannotMiss",                  type: "Electric" , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Water Pulse"   : { name: "Water Pulse",   battleEffect:  null,                         type: "Water"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Doom Desire"   : { name: "Doom Desire",   battleEffect: "FutureAttack",                type: "Steel"    , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
	"Psycho Boost"  : { name: "Psycho Boost",  battleEffect: "DamageAndUserSpattackDown2",  type: "Psychic"  , damageFormula: DamageFormulaType.STANDARD_DAMAGE     }, 
}