const moves = { 
	"Pound"         : { name: "Pound",         battleEffect:  null,                         damageType: "Normal"   }, 
	"Karate Chop"   : { name: "Karate Chop",   battleEffect: "HighCritical",                damageType: "Fighting" }, 
	"DoubleSlap"    : { name: "DoubleSlap",    battleEffect:  null,                         damageType: "Normal"   }, 
	"Comet Punch"   : { name: "Comet Punch",   battleEffect:  null,                         damageType: "Normal"   }, 
	"Mega Punch"    : { name: "Mega Punch",    battleEffect:  null,                         damageType: "Normal"   }, 
	"Pay Day"       : { name: "Pay Day",       battleEffect:  null,                         damageType: "Normal"   }, 
	"Fire Punch"    : { name: "Fire Punch",    battleEffect:  null,                         damageType: "Fire"     }, 
	"Ice Punch"     : { name: "Ice Punch",     battleEffect:  null,                         damageType: "Ice"      }, 
	"ThunderPunch"  : { name: "ThunderPunch",  battleEffect:  null,                         damageType: "Electric" }, 
	"Scratch"       : { name: "Scratch",       battleEffect:  null,                         damageType: "Normal"   }, 
	"ViceGrip"      : { name: "ViceGrip",      battleEffect:  null,                         damageType: "Normal"   }, 
	"Guillotine"    : { name: "Guillotine",    battleEffect: "Ohko",                        damageType:  null      }, 
	"Razor Wind"    : { name: "Razor Wind",    battleEffect: "RazorWind",                   damageType: "Normal"   }, 
	"Swords Dance"  : { name: "Swords Dance",  battleEffect: "UserAttackUp2",               damageType:  null      }, 
	"Cut"           : { name: "Cut",           battleEffect:  null,                         damageType: "Normal"   }, 
	"Gust"          : { name: "Gust",          battleEffect:  null,                         damageType: "Flying"   }, 
	"Wing Attack"   : { name: "Wing Attack",   battleEffect:  null,                         damageType: "Flying"   }, 
	"Whirlwind"     : { name: "Whirlwind",     battleEffect: "ForceSwitch",                 damageType:  null      }, 
	"Fly"           : { name: "Fly",           battleEffect: "Fly",                         damageType: "Flying"   }, 
	"Bind"          : { name: "Bind",          battleEffect: "Trap",                        damageType: "Normal"   }, 
	"Slam"          : { name: "Slam",          battleEffect:  null,                         damageType: "Normal"   }, 
	"Vine Whip"     : { name: "Vine Whip",     battleEffect:  null,                         damageType: "Grass"    }, 
	"Stomp"         : { name: "Stomp",         battleEffect:  null,                         damageType: "Normal"   }, 
	"Double Kick"   : { name: "Double Kick",   battleEffect:  null,                         damageType: "Fighting" }, 
	"Mega Kick"     : { name: "Mega Kick",     battleEffect:  null,                         damageType: "Normal"   }, 
	"Jump Kick"     : { name: "Jump Kick",     battleEffect:  null,                         damageType: "Fighting" }, 
	"Rolling Kick"  : { name: "Rolling Kick",  battleEffect:  null,                         damageType: "Fighting" }, 
	"Sand-Attack"   : { name: "Sand-Attack",   battleEffect: "TargetAccuracyDown1",         damageType:  null      }, 
	"Headbutt"      : { name: "Headbutt",      battleEffect:  null,                         damageType: "Normal"   }, 
	"Horn Attack"   : { name: "Horn Attack",   battleEffect:  null,                         damageType: "Normal"   }, 
	"Fury Attack"   : { name: "Fury Attack",   battleEffect:  null,                         damageType: "Normal"   }, 
	"Horn Drill"    : { name: "Horn Drill",    battleEffect: "Ohko",                        damageType:  null      }, 
	"Tackle"        : { name: "Tackle",        battleEffect:  null,                         damageType: "Normal"   }, 
	"Body Slam"     : { name: "Body Slam",     battleEffect:  null,                         damageType: "Normal"   }, 
	"Wrap"          : { name: "Wrap",          battleEffect: "Trap",                        damageType: "Normal"   }, 
	"Take Down"     : { name: "Take Down",     battleEffect: "14Recoil",                    damageType: "Normal"   }, 
	"Thrash"        : { name: "Thrash",        battleEffect:  null,                         damageType: "Normal"   }, 
	"Double-Edge"   : { name: "Double-Edge",   battleEffect: "13Recoil",                    damageType: "Normal"   }, 
	"Tail Whip"     : { name: "Tail Whip",     battleEffect: "TargetDefenseDown1",          damageType:  null      }, 
	"Poison Sting"  : { name: "Poison Sting",  battleEffect:  null,                         damageType: "Poison"   }, 
	"Twineedle"     : { name: "Twineedle",     battleEffect:  null,                         damageType: "Bug"      }, 
	"Pin Missile"   : { name: "Pin Missile",   battleEffect:  null,                         damageType: "Bug"      }, 
	"Leer"          : { name: "Leer",          battleEffect: "TargetDefenseDown1",          damageType:  null      }, 
	"Bite"          : { name: "Bite",          battleEffect:  null,                         damageType: "Dark"     }, 
	"Growl"         : { name: "Growl",         battleEffect: "TargetAttackDown1",           damageType:  null      }, 
	"Roar"          : { name: "Roar",          battleEffect: "ForceSwitch",                 damageType:  null      }, 
	"Sing"          : { name: "Sing",          battleEffect: "InflictSleep",                damageType:  null      }, 
	"Supersonic"    : { name: "Supersonic",    battleEffect: "InflictConfusion",            damageType:  null      }, 
	"SonicBoom"     : { name: "SonicBoom",     battleEffect: "Sonicboom",                   damageType: "Normal"   }, 
	"Disable"       : { name: "Disable",       battleEffect: "Disable",                     damageType:  null      }, 
	"Acid"          : { name: "Acid",          battleEffect:  null,                         damageType: "Poison"   }, 
	"Ember"         : { name: "Ember",         battleEffect:  null,                         damageType: "Fire"     }, 
	"Flamethrower"  : { name: "Flamethrower",  battleEffect:  null,                         damageType: "Fire"     }, 
	"Mist"          : { name: "Mist",          battleEffect: "Mist",                        damageType:  null      }, 
	"Water Gun"     : { name: "Water Gun",     battleEffect:  null,                         damageType: "Water"    }, 
	"Hydro Pump"    : { name: "Hydro Pump",    battleEffect:  null,                         damageType: "Water"    }, 
	"Surf"          : { name: "Surf",          battleEffect:  null,                         damageType: "Water"    }, 
	"Ice Beam"      : { name: "Ice Beam",      battleEffect:  null,                         damageType: "Ice"      }, 
	"Blizzard"      : { name: "Blizzard",      battleEffect: "Blizzard",                    damageType: "Ice"      }, 
	"Psybeam"       : { name: "Psybeam",       battleEffect:  null,                         damageType: "Psychic"  }, 
	"BubbleBeam"    : { name: "BubbleBeam",    battleEffect: "DamageAndTargetSpeedDown1",   damageType: "Water"    }, 
	"Aurora Beam"   : { name: "Aurora Beam",   battleEffect:  null,                         damageType: "Ice"      }, 
	"Hyper Beam"    : { name: "Hyper Beam",    battleEffect: "MustRecharge",                damageType: "Normal"   }, 
	"Peck"          : { name: "Peck",          battleEffect:  null,                         damageType: "Flying"   }, 
	"Drill Peck"    : { name: "Drill Peck",    battleEffect:  null,                         damageType: "Flying"   }, 
	"Submission"    : { name: "Submission",    battleEffect: "14Recoil",                    damageType: "Fighting" }, 
	"Low Kick"      : { name: "Low Kick",      battleEffect: "DamageByTargetWeight",        damageType: "Fighting" }, 
	"Counter"       : { name: "Counter",       battleEffect: "Counter",                     damageType:  null      }, 
	"Seismic Toss"  : { name: "Seismic Toss",  battleEffect: "DamageIsLevel",               damageType: "Fighting" }, 
	"Strength"      : { name: "Strength",      battleEffect:  null,                         damageType: "Normal"   }, 
	"Absorb"        : { name: "Absorb",        battleEffect: "HpDrain",                     damageType: "Grass"    }, 
	"Mega Drain"    : { name: "Mega Drain",    battleEffect: "HpDrain",                     damageType: "Grass"    }, 
	"Leech Seed"    : { name: "Leech Seed",    battleEffect: "LeechSeed",                   damageType:  null      }, 
	"Growth"        : { name: "Growth",        battleEffect: "UserSpattackUp1",             damageType:  null      }, 
	"Razor Leaf"    : { name: "Razor Leaf",    battleEffect: "HighCritical",                damageType: "Grass"    }, 
	"SolarBeam"     : { name: "SolarBeam",     battleEffect: "Solarbeam",                   damageType: "Grass"    }, 
	"PoisonPowder"  : { name: "PoisonPowder",  battleEffect: "InflictPoison",               damageType:  null      }, 
	"Stun Spore"    : { name: "Stun Spore",    battleEffect: "InflictParalysis",            damageType:  null      }, 
	"Sleep Powder"  : { name: "Sleep Powder",  battleEffect: "InflictSleep",                damageType:  null      }, 
	"Petal Dance"   : { name: "Petal Dance",   battleEffect:  null,                         damageType: "Grass"    }, 
	"String Shot"   : { name: "String Shot",   battleEffect: "TargetSpeedDown1",            damageType:  null      }, 
	"Dragon Rage"   : { name: "Dragon Rage",   battleEffect: "DragonRage",                  damageType: "Dragon"   }, 
	"Fire Spin"     : { name: "Fire Spin",     battleEffect: "Trap",                        damageType: "Fire"     }, 
	"ThunderShock"  : { name: "ThunderShock",  battleEffect:  null,                         damageType: "Electric" }, 
	"Thunderbolt"   : { name: "Thunderbolt",   battleEffect:  null,                         damageType: "Electric" }, 
	"Thunder Wave"  : { name: "Thunder Wave",  battleEffect: "InflictParalysis",            damageType:  null      }, 
	"Thunder"       : { name: "Thunder",       battleEffect:  null,                         damageType: "Electric" }, 
	"Rock Throw"    : { name: "Rock Throw",    battleEffect:  null,                         damageType: "Rock"     }, 
	"Earthquake"    : { name: "Earthquake",    battleEffect:  null,                         damageType: "Ground"   }, 
	"Fissure"       : { name: "Fissure",       battleEffect: "Ohko",                        damageType:  null      }, 
	"Dig"           : { name: "Dig",           battleEffect: "Dig",                         damageType: "Ground"   }, 
	"Toxic"         : { name: "Toxic",         battleEffect: "Toxic",                       damageType:  null      }, 
	"Confusion"     : { name: "Confusion",     battleEffect:  null,                         damageType: "Psychic"  }, 
	"Psychic"       : { name: "Psychic",       battleEffect:  null,                         damageType: "Psychic"  }, 
	"Hypnosis"      : { name: "Hypnosis",      battleEffect: "InflictSleep",                damageType:  null      }, 
	"Meditate"      : { name: "Meditate",      battleEffect: "UserAttackUp1",               damageType:  null      }, 
	"Agility"       : { name: "Agility",       battleEffect: "UserSpeedUp2",                damageType:  null      }, 
	"Quick Attack"  : { name: "Quick Attack",  battleEffect: "Priority",                    damageType: "Normal"   }, 
	"Rage"          : { name: "Rage",          battleEffect:  null,                         damageType: "Normal"   }, 
	"Teleport"      : { name: "Teleport",      battleEffect: "Teleport",                    damageType:  null      }, 
	"Night Shade"   : { name: "Night Shade",   battleEffect: "DamageIsLevel",               damageType: "Ghost"    }, 
	"Mimic"         : { name: "Mimic",         battleEffect:  null,                         damageType:  null      }, 
	"Screech"       : { name: "Screech",       battleEffect: "TargetDefenseDown2",          damageType:  null      }, 
	"Double Team"   : { name: "Double Team",   battleEffect: "UserEvasionUp1",              damageType:  null      }, 
	"Recover"       : { name: "Recover",       battleEffect: "Recover",                     damageType:  null      }, 
	"Harden"        : { name: "Harden",        battleEffect: "UserDefenseUp1",              damageType:  null      }, 
	"Minimize"      : { name: "Minimize",      battleEffect: "Minimize",                    damageType:  null      }, 
	"SmokeScreen"   : { name: "SmokeScreen",   battleEffect: "TargetAccuracyDown1",         damageType:  null      }, 
	"Confuse Ray"   : { name: "Confuse Ray",   battleEffect: "InflictConfusion",            damageType:  null      }, 
	"Withdraw"      : { name: "Withdraw",      battleEffect: "UserDefenseUp1",              damageType:  null      }, 
	"Defense Curl"  : { name: "Defense Curl",  battleEffect: "DefenseCurl",                 damageType:  null      }, 
	"Barrier"       : { name: "Barrier",       battleEffect: "UserDefenseUp2",              damageType:  null      }, 
	"Light Screen"  : { name: "Light Screen",  battleEffect: "LightScreen",                 damageType:  null      }, 
	"Haze"          : { name: "Haze",          battleEffect: "Haze",                        damageType:  null      }, 
	"Reflect"       : { name: "Reflect",       battleEffect: "Reflect",                     damageType:  null      }, 
	"Focus Energy"  : { name: "Focus Energy",  battleEffect: "FocusEnergy",                 damageType:  null      }, 
	"Bide"          : { name: "Bide",          battleEffect: "Bide",                        damageType:  null      }, 
	"Metronome"     : { name: "Metronome",     battleEffect:  null,                         damageType:  null      }, 
	"Mirror Move"   : { name: "Mirror Move",   battleEffect: "MirrorMove",                  damageType:  null      }, 
	"Selfdestruct"  : { name: "Selfdestruct",  battleEffect: "Selfdestruction",             damageType: "Normal"   }, 
	"Egg Bomb"      : { name: "Egg Bomb",      battleEffect:  null,                         damageType: "Normal"   }, 
	"Lick"          : { name: "Lick",          battleEffect:  null,                         damageType: "Ghost"    }, 
	"Smog"          : { name: "Smog",          battleEffect:  null,                         damageType: "Poison"   }, 
	"Sludge"        : { name: "Sludge",        battleEffect:  null,                         damageType: "Poison"   }, 
	"Bone Club"     : { name: "Bone Club",     battleEffect:  null,                         damageType: "Ground"   }, 
	"Fire Blast"    : { name: "Fire Blast",    battleEffect:  null,                         damageType: "Fire"     }, 
	"Waterfall"     : { name: "Waterfall",     battleEffect:  null,                         damageType: "Water"    }, 
	"Clamp"         : { name: "Clamp",         battleEffect: "Trap",                        damageType: "Water"    }, 
	"Swift"         : { name: "Swift",         battleEffect: "CannotMiss",                  damageType: "Normal"   }, 
	"Skull Bash"    : { name: "Skull Bash",    battleEffect: "SkullBash",                   damageType: "Normal"   }, 
	"Spike Cannon"  : { name: "Spike Cannon",  battleEffect:  null,                         damageType: "Normal"   }, 
	"Constrict"     : { name: "Constrict",     battleEffect: "DamageAndTargetSpeedDown1",   damageType: "Normal"   }, 
	"Amnesia"       : { name: "Amnesia",       battleEffect: "UserSpdefenseUp2",            damageType:  null      }, 
	"Kinesis"       : { name: "Kinesis",       battleEffect: "TargetAccuracyDown1",         damageType:  null      }, 
	"Softboiled"    : { name: "Softboiled",    battleEffect: "Recover",                     damageType:  null      }, 
	"Hi Jump Kick"  : { name: "Hi Jump Kick",  battleEffect:  null,                         damageType: "Fighting" }, 
	"Glare"         : { name: "Glare",         battleEffect: "InflictParalysis",            damageType:  null      }, 
	"Dream Eater"   : { name: "Dream Eater",   battleEffect: "DreamEater",                  damageType: "Psychic"  }, 
	"Poison Gas"    : { name: "Poison Gas",    battleEffect: "InflictPoison",               damageType:  null      }, 
	"Barrage"       : { name: "Barrage",       battleEffect:  null,                         damageType: "Normal"   }, 
	"Leech Life"    : { name: "Leech Life",    battleEffect: "HpDrain",                     damageType: "Bug"      }, 
	"Lovely Kiss"   : { name: "Lovely Kiss",   battleEffect: "InflictSleep",                damageType:  null      }, 
	"Sky Attack"    : { name: "Sky Attack",    battleEffect: "SkyAttack",                   damageType: "Flying"   }, 
	"Transform"     : { name: "Transform",     battleEffect:  null,                         damageType:  null      }, 
	"Bubble"        : { name: "Bubble",        battleEffect: "DamageAndTargetSpeedDown1",   damageType: "Water"    }, 
	"Dizzy Punch"   : { name: "Dizzy Punch",   battleEffect:  null,                         damageType: "Normal"   }, 
	"Spore"         : { name: "Spore",         battleEffect: "InflictSleep",                damageType:  null      }, 
	"Flash"         : { name: "Flash",         battleEffect: "TargetAccuracyDown1",         damageType:  null      }, 
	"Psywave"       : { name: "Psywave",       battleEffect: "Psywave",                     damageType: "Psychic"  }, 
	"Splash"        : { name: "Splash",        battleEffect: "NoDamage",                    damageType:  null      }, 
	"Acid Armor"    : { name: "Acid Armor",    battleEffect: "UserDefenseUp2",              damageType:  null      }, 
	"Crabhammer"    : { name: "Crabhammer",    battleEffect: "HighCritical",                damageType: "Water"    }, 
	"Explosion"     : { name: "Explosion",     battleEffect: "Selfdestruction",             damageType: "Normal"   }, 
	"Fury Swipes"   : { name: "Fury Swipes",   battleEffect:  null,                         damageType: "Normal"   }, 
	"Bonemerang"    : { name: "Bonemerang",    battleEffect:  null,                         damageType: "Ground"   }, 
	"Rest"          : { name: "Rest",          battleEffect: "Rest",                        damageType:  null      }, 
	"Rock Slide"    : { name: "Rock Slide",    battleEffect:  null,                         damageType: "Rock"     }, 
	"Hyper Fang"    : { name: "Hyper Fang",    battleEffect:  null,                         damageType: "Normal"   }, 
	"Sharpen"       : { name: "Sharpen",       battleEffect: "UserAttackUp1",               damageType:  null      }, 
	"Conversion"    : { name: "Conversion",    battleEffect: "Conversion",                  damageType:  null      }, 
	"Tri Attack"    : { name: "Tri Attack",    battleEffect:  null,                         damageType: "Normal"   }, 
	"Super Fang"    : { name: "Super Fang",    battleEffect: "SuperFang",                   damageType:  null      }, 
	"Slash"         : { name: "Slash",         battleEffect: "HighCritical",                damageType: "Normal"   }, 
	"Substitute"    : { name: "Substitute",    battleEffect: "Substitute",                  damageType:  null      }, 
//	"Struggle"      : { name: "Struggle",      battleEffect:  null,                         damageType: "Normal"   }, 
	"Sketch"        : { name: "Sketch",        battleEffect:  null,                         damageType:  null      }, 
	"Triple Kick"   : { name: "Triple Kick",   battleEffect:  null,                         damageType: "Fighting" }, 
	"Thief"         : { name: "Thief",         battleEffect: "StealItem",                   damageType: "Dark"     }, 
	"Spider Web"    : { name: "Spider Web",    battleEffect: "BlockEscape",                 damageType:  null      }, 
	"Mind Reader"   : { name: "Mind Reader",   battleEffect: "LockOn",                      damageType:  null      }, 
	"Nightmare"     : { name: "Nightmare",     battleEffect: "Nightmare",                   damageType:  null      }, 
	"Flame Wheel"   : { name: "Flame Wheel",   battleEffect:  null,                         damageType: "Fire"     }, 
	"Snore"         : { name: "Snore",         battleEffect: "Snore",                       damageType: "Normal"   }, 
	"Curse"         : { name: "Curse",         battleEffect: "Curse",                       damageType:  null      }, 
	"Flail"         : { name: "Flail",         battleEffect: "LowHpHighDamage",             damageType:  null      }, 
	"Conversion2"   : { name: "Conversion2",   battleEffect: "Conversion2",                 damageType:  null      }, 
	"Aeroblast"     : { name: "Aeroblast",     battleEffect: "HighCritical",                damageType: "Flying"   }, 
	"Cotton Spore"  : { name: "Cotton Spore",  battleEffect: "TargetSpeedDown2",            damageType:  null      }, 
	"Reversal"      : { name: "Reversal",      battleEffect: "LowHpHighDamage",             damageType:  null      }, 
	"Spite"         : { name: "Spite",         battleEffect:  null,                         damageType:  null      }, 
	"Powder Snow"   : { name: "Powder Snow",   battleEffect:  null,                         damageType: "Ice"      }, 
	"Protect"       : { name: "Protect",       battleEffect: "Protect",                     damageType:  null      }, 
	"Mach Punch"    : { name: "Mach Punch",    battleEffect: "Priority",                    damageType: "Fighting" }, 
	"Scary Face"    : { name: "Scary Face",    battleEffect: "TargetSpeedDown2",            damageType:  null      }, 
	"Faint Attack"  : { name: "Faint Attack",  battleEffect: "CannotMiss",                  damageType: "Dark"     }, 
	"Sweet Kiss"    : { name: "Sweet Kiss",    battleEffect: "InflictConfusion",            damageType:  null      }, 
	"Belly Drum"    : { name: "Belly Drum",    battleEffect: "BellyDrum",                   damageType:  null      }, 
	"Sludge Bomb"   : { name: "Sludge Bomb",   battleEffect:  null,                         damageType: "Poison"   }, 
	"Mud-Slap"      : { name: "Mud-Slap",      battleEffect:  null,                         damageType: "Ground"   }, 
	"Octazooka"     : { name: "Octazooka",     battleEffect:  null,                         damageType: "Water"    }, 
	"Spikes"        : { name: "Spikes",        battleEffect: "Spikes",                      damageType:  null      }, 
	"Zap Cannon"    : { name: "Zap Cannon",    battleEffect:  null,                         damageType: "Electric" }, 
	"Foresight"     : { name: "Foresight",     battleEffect: "Identify",                    damageType:  null      }, 
	"Destiny Bond"  : { name: "Destiny Bond",  battleEffect: "DestinyBond",                 damageType:  null      }, 
	"Perish Song"   : { name: "Perish Song",   battleEffect: "PerishSong",                  damageType:  null      }, 
	"Icy Wind"      : { name: "Icy Wind",      battleEffect: "DamageAndTargetSpeedDown1",   damageType: "Ice"      }, 
	"Detect"        : { name: "Detect",        battleEffect: "Protect",                     damageType:  null      }, 
	"Bone Rush"     : { name: "Bone Rush",     battleEffect:  null,                         damageType: "Ground"   }, 
	"Lock-On"       : { name: "Lock-On",       battleEffect: "LockOn",                      damageType:  null      }, 
	"Outrage"       : { name: "Outrage",       battleEffect:  null,                         damageType: "Dragon"   }, 
	"Sandstorm"     : { name: "Sandstorm",     battleEffect: "Sandstorm",                   damageType:  null      }, 
	"Giga Drain"    : { name: "Giga Drain",    battleEffect: "HpDrain",                     damageType: "Grass"    }, 
	"Endure"        : { name: "Endure",        battleEffect: "Endure",                      damageType:  null      }, 
	"Charm"         : { name: "Charm",         battleEffect: "TargetAttackDown2",           damageType:  null      }, 
	"Rollout"       : { name: "Rollout",       battleEffect:  null,                         damageType: "Rock"     }, 
	"False Swipe"   : { name: "False Swipe",   battleEffect:  null,                         damageType: "Normal"   }, 
	"Swagger"       : { name: "Swagger",       battleEffect: "Swagger",                     damageType:  null      }, 
	"Milk Drink"    : { name: "Milk Drink",    battleEffect: "Recover",                     damageType:  null      }, 
	"Spark"         : { name: "Spark",         battleEffect:  null,                         damageType: "Electric" }, 
	"Fury Cutter"   : { name: "Fury Cutter",   battleEffect:  null,                         damageType: "Bug"      }, 
	"Steel Wing"    : { name: "Steel Wing",    battleEffect:  null,                         damageType: "Steel"    }, 
	"Mean Look"     : { name: "Mean Look",     battleEffect: "BlockEscape",                 damageType:  null      }, 
	"Attract"       : { name: "Attract",       battleEffect: "Attract",                     damageType:  null      }, 
	"Sleep Talk"    : { name: "Sleep Talk",    battleEffect: "SleepTalk",                   damageType:  null      }, 
	"Heal Bell"     : { name: "Heal Bell",     battleEffect: "HealBell",                    damageType:  null      }, 
	"Return"        : { name: "Return",        battleEffect: "Return",                      damageType: "Normal"   }, 
	"Present"       : { name: "Present",       battleEffect: "Present",                     damageType:  null      }, 
	"Frustration"   : { name: "Frustration",   battleEffect: "Frustration",                 damageType: "Normal"   }, 
	"Safeguard"     : { name: "Safeguard",     battleEffect: "Safeguard",                   damageType:  null      }, 
	"Pain Split"    : { name: "Pain Split",    battleEffect: "PainSplit",                   damageType:  null      }, 
	"Sacred Fire"   : { name: "Sacred Fire",   battleEffect:  null,                         damageType: "Fire"     }, 
	"Magnitude"     : { name: "Magnitude",     battleEffect: "Magnitude",                   damageType:  null      }, 
	"DynamicPunch"  : { name: "DynamicPunch",  battleEffect:  null,                         damageType: "Fighting" }, 
	"Megahorn"      : { name: "Megahorn",      battleEffect:  null,                         damageType: "Bug"      }, 
	"DragonBreath"  : { name: "DragonBreath",  battleEffect:  null,                         damageType: "Dragon"   }, 
	"Baton Pass"    : { name: "Baton Pass",    battleEffect: "BatonPass",                   damageType:  null      }, 
	"Encore"        : { name: "Encore",        battleEffect: "Encore",                      damageType:  null      }, 
	"Pursuit"       : { name: "Pursuit",       battleEffect: "Pursuit",                     damageType: "Dark"     }, 
	"Rapid Spin"    : { name: "Rapid Spin",    battleEffect:  null,                         damageType: "Normal"   }, 
	"Sweet Scent"   : { name: "Sweet Scent",   battleEffect: "TargetEvasionDown1",          damageType:  null      }, 
	"Iron Tail"     : { name: "Iron Tail",     battleEffect:  null,                         damageType: "Steel"    }, 
	"Metal Claw"    : { name: "Metal Claw",    battleEffect:  null,                         damageType: "Steel"    }, 
	"Vital Throw"   : { name: "Vital Throw",   battleEffect: "VitalThrow",                  damageType: "Fighting" }, 
	"Morning Sun"   : { name: "Morning Sun",   battleEffect: "SunRecover",                  damageType:  null      }, 
	"Synthesis"     : { name: "Synthesis",     battleEffect: "SunRecover",                  damageType:  null      }, 
	"Moonlight"     : { name: "Moonlight",     battleEffect: "SunRecover",                  damageType:  null      }, 
	"Hidden Power"  : { name: "Hidden Power",  battleEffect: "HiddenPower",                 damageType:  null      }, 
	"Cross Chop"    : { name: "Cross Chop",    battleEffect: "HighCritical",                damageType: "Fighting" }, 
	"Twister"       : { name: "Twister",       battleEffect:  null,                         damageType: "Dragon"   }, 
	"Rain Dance"    : { name: "Rain Dance",    battleEffect: "RainDance",                   damageType:  null      }, 
	"Sunny Day"     : { name: "Sunny Day",     battleEffect: "SunnyDay",                    damageType:  null      }, 
	"Crunch"        : { name: "Crunch",        battleEffect:  null,                         damageType: "Dark"     }, 
	"Mirror Coat"   : { name: "Mirror Coat",   battleEffect: "MirrorCoat",                  damageType:  null      }, 
	"Psych Up"      : { name: "Psych Up",      battleEffect: "PsychUp",                     damageType:  null      }, 
	"ExtremeSpeed"  : { name: "ExtremeSpeed",  battleEffect: "Priority",                    damageType: "Normal"   }, 
	"AncientPower"  : { name: "AncientPower",  battleEffect:  null,                         damageType: "Rock"     }, 
	"Shadow Ball"   : { name: "Shadow Ball",   battleEffect:  null,                         damageType: "Ghost"    }, 
	"Future Sight"  : { name: "Future Sight",  battleEffect: "FutureAttack",                damageType: "Psychic"  }, 
	"Rock Smash"    : { name: "Rock Smash",    battleEffect:  null,                         damageType: "Fighting" }, 
	"Whirlpool"     : { name: "Whirlpool",     battleEffect:  null,                         damageType: "Water"    }, 
	"Beat Up"       : { name: "Beat Up",       battleEffect:  null,                         damageType: "Dark"     }, 
	"Fake Out"      : { name: "Fake Out",      battleEffect: "FakeOut",                     damageType: "Normal"   }, 
	"Uproar"        : { name: "Uproar",        battleEffect:  null,                         damageType: "Normal"   }, 
	"Stockpile"     : { name: "Stockpile",     battleEffect: "Stockpile",                   damageType:  null      }, 
	"Spit Up"       : { name: "Spit Up",       battleEffect: "SpitUp",                      damageType: "Normal"   }, 
	"Swallow"       : { name: "Swallow",       battleEffect: "Swallow",                     damageType:  null      }, 
	"Heat Wave"     : { name: "Heat Wave",     battleEffect:  null,                         damageType: "Fire"     }, 
	"Hail"          : { name: "Hail",          battleEffect: "Hail",                        damageType:  null      }, 
	"Torment"       : { name: "Torment",       battleEffect: "Torment",                     damageType:  null      }, 
	"Flatter"       : { name: "Flatter",       battleEffect: "Flatter",                     damageType:  null      }, 
	"Will-O-Wisp"   : { name: "Will-O-Wisp",   battleEffect: "InflictBurn",                 damageType:  null      }, 
	"Memento"       : { name: "Memento",       battleEffect: "Memento",                     damageType:  null      }, 
	"Facade"        : { name: "Facade",        battleEffect: "Facade",                      damageType: "Normal"   }, 
	"Focus Punch"   : { name: "Focus Punch",   battleEffect: "FocusPunch",                  damageType: "Fighting" }, 
	"SmellingSalt"  : { name: "SmellingSalt",  battleEffect: "Smellingsalt",                damageType: "Normal"   }, 
	"Follow Me"     : { name: "Follow Me",     battleEffect: "FollowMe",                    damageType:  null      }, 
	"Nature Power"  : { name: "Nature Power",  battleEffect:  null,                         damageType:  null      }, 
	"Charge"        : { name: "Charge",        battleEffect: "Charge",                      damageType:  null      }, 
	"Taunt"         : { name: "Taunt",         battleEffect:  null,                         damageType:  null      }, 
	"Helping Hand"  : { name: "Helping Hand",  battleEffect: "HelpingHand",                 damageType:  null      }, 
	"Trick"         : { name: "Trick",         battleEffect: "SwitchItems",                 damageType:  null      }, 
	"Role Play"     : { name: "Role Play",     battleEffect: "RolePlay",                    damageType:  null      }, 
	"Wish"          : { name: "Wish",          battleEffect:  null,                         damageType:  null      }, 
	"Assist"        : { name: "Assist",        battleEffect:  null,                         damageType:  null      }, 
	"Ingrain"       : { name: "Ingrain",       battleEffect: "Ingrain",                     damageType:  null      }, 
	"Superpower"    : { name: "Superpower",    battleEffect: "Superpower",                  damageType: "Fighting" }, 
	"Magic Coat"    : { name: "Magic Coat",    battleEffect: "MagicCoat",                   damageType:  null      }, 
	"Recycle"       : { name: "Recycle",       battleEffect: "Recycle",                     damageType:  null      }, 
	"Revenge"       : { name: "Revenge",       battleEffect: "DamageRevenge",               damageType: "Fighting" }, 
	"Brick Break"   : { name: "Brick Break",   battleEffect: "BrickBreak",                  damageType: "Fighting" }, 
	"Yawn"          : { name: "Yawn",          battleEffect: "Yawn",                        damageType:  null      }, 
	"Knock Off"     : { name: "Knock Off",     battleEffect: "KnockOff",                    damageType: "Dark"     }, 
	"Endeavor"      : { name: "Endeavor",      battleEffect: "Endeavor",                    damageType:  null      }, 
	"Eruption"      : { name: "Eruption",      battleEffect: "HighHpHighDamage",            damageType: "Fire"     }, 
	"Skill Swap"    : { name: "Skill Swap",    battleEffect: "SkillSwap",                   damageType:  null      }, 
	"Imprison"      : { name: "Imprison",      battleEffect: "Imprison",                    damageType:  null      }, 
	"Refresh"       : { name: "Refresh",       battleEffect: "Refresh",                     damageType:  null      }, 
	"Grudge"        : { name: "Grudge",        battleEffect: "Grudge",                      damageType:  null      }, 
	"Snatch"        : { name: "Snatch",        battleEffect: "Snatch",                      damageType:  null      }, 
	"Secret Power"  : { name: "Secret Power",  battleEffect:  null,                         damageType: "Normal"   }, 
	"Dive"          : { name: "Dive",          battleEffect: "Dive",                        damageType: "Water"    }, 
	"Arm Thrust"    : { name: "Arm Thrust",    battleEffect:  null,                         damageType: "Fighting" }, 
	"Camouflage"    : { name: "Camouflage",    battleEffect: "Camouflage",                  damageType:  null      }, 
	"Tail Glow"     : { name: "Tail Glow",     battleEffect: "UserSpattackUp2",             damageType:  null      }, 
	"Luster Purge"  : { name: "Luster Purge",  battleEffect:  null,                         damageType: "Psychic"  }, 
	"Mist Ball"     : { name: "Mist Ball",     battleEffect:  null,                         damageType: "Psychic"  }, 
	"FeatherDance"  : { name: "FeatherDance",  battleEffect: "TargetAttackDown2",           damageType:  null      }, 
	"Teeter Dance"  : { name: "Teeter Dance",  battleEffect: "TeeterDance",                 damageType:  null      }, 
	"Blaze Kick"    : { name: "Blaze Kick",    battleEffect: "BlazeKick",                   damageType: "Fire"     }, 
	"Mud Sport"     : { name: "Mud Sport",     battleEffect: "MudSport",                    damageType:  null      }, 
	"Ice Ball"      : { name: "Ice Ball",      battleEffect:  null,                         damageType: "Ice"      }, 
	"Needle Arm"    : { name: "Needle Arm",    battleEffect:  null,                         damageType: "Grass"    }, 
	"Slack Off"     : { name: "Slack Off",     battleEffect: "Recover",                     damageType:  null      }, 
	"Hyper Voice"   : { name: "Hyper Voice",   battleEffect:  null,                         damageType: "Normal"   }, 
	"Poison Fang"   : { name: "Poison Fang",   battleEffect:  null,                         damageType: "Poison"   }, 
	"Crush Claw"    : { name: "Crush Claw",    battleEffect:  null,                         damageType: "Normal"   }, 
	"Blast Burn"    : { name: "Blast Burn",    battleEffect: "MustRecharge",                damageType: "Fire"     }, 
	"Hydro Cannon"  : { name: "Hydro Cannon",  battleEffect: "MustRecharge",                damageType: "Water"    }, 
	"Meteor Mash"   : { name: "Meteor Mash",   battleEffect:  null,                         damageType: "Steel"    }, 
	"Astonish"      : { name: "Astonish",      battleEffect:  null,                         damageType: "Ghost"    }, 
	"Weather Ball"  : { name: "Weather Ball",  battleEffect:  null,                         damageType: "Normal"   }, 
	"Aromatherapy"  : { name: "Aromatherapy",  battleEffect: "HealBell",                    damageType:  null      }, 
	"Fake Tears"    : { name: "Fake Tears",    battleEffect: "TargetSpdefenseDown2",        damageType:  null      }, 
	"Air Cutter"    : { name: "Air Cutter",    battleEffect: "HighCritical",                damageType: "Flying"   }, 
	"Overheat"      : { name: "Overheat",      battleEffect: "DamageAndUserSpattackDown2",  damageType: "Fire"     }, 
	"Odor Sleuth"   : { name: "Odor Sleuth",   battleEffect: "Identify",                    damageType:  null      }, 
	"Rock Tomb"     : { name: "Rock Tomb",     battleEffect: "DamageAndTargetSpeedDown1",   damageType: "Rock"     }, 
	"Silver Wind"   : { name: "Silver Wind",   battleEffect:  null,                         damageType: "Bug"      }, 
	"Metal Sound"   : { name: "Metal Sound",   battleEffect: "TargetSpdefenseDown2",        damageType:  null      }, 
	"GrassWhistle"  : { name: "GrassWhistle",  battleEffect: "InflictSleep",                damageType:  null      }, 
	"Tickle"        : { name: "Tickle",        battleEffect: "Tickle",                      damageType:  null      }, 
	"Cosmic Power"  : { name: "Cosmic Power",  battleEffect: "BothDefenseUp1",              damageType:  null      }, 
	"Water Spout"   : { name: "Water Spout",   battleEffect: "HighHpHighDamage",            damageType: "Water"    }, 
	"Signal Beam"   : { name: "Signal Beam",   battleEffect:  null,                         damageType: "Bug"      }, 
	"Shadow Punch"  : { name: "Shadow Punch",  battleEffect: "CannotMiss",                  damageType: "Ghost"    }, 
	"Extrasensory"  : { name: "Extrasensory",  battleEffect:  null,                         damageType: "Psychic"  }, 
	"Sky Uppercut"  : { name: "Sky Uppercut",  battleEffect:  null,                         damageType: "Fighting" }, 
	"Sand Tomb"     : { name: "Sand Tomb",     battleEffect: "Trap",                        damageType: "Ground"   }, 
	"Sheer Cold"    : { name: "Sheer Cold",    battleEffect: "Ohko",                        damageType:  null      }, 
	"Muddy Water"   : { name: "Muddy Water",   battleEffect:  null,                         damageType: "Water"    }, 
	"Bullet Seed"   : { name: "Bullet Seed",   battleEffect:  null,                         damageType: "Grass"    }, 
	"Aerial Ace"    : { name: "Aerial Ace",    battleEffect: "CannotMiss",                  damageType: "Flying"   }, 
	"Icicle Spear"  : { name: "Icicle Spear",  battleEffect:  null,                         damageType: "Ice"      }, 
	"Iron Defense"  : { name: "Iron Defense",  battleEffect: "UserDefenseUp2",              damageType:  null      }, 
	"Block"         : { name: "Block",         battleEffect: "BlockEscape",                 damageType:  null      }, 
	"Howl"          : { name: "Howl",          battleEffect: "UserAttackUp1",               damageType:  null      }, 
	"Dragon Claw"   : { name: "Dragon Claw",   battleEffect:  null,                         damageType: "Dragon"   }, 
	"Frenzy Plant"  : { name: "Frenzy Plant",  battleEffect: "MustRecharge",                damageType: "Grass"    }, 
	"Bulk Up"       : { name: "Bulk Up",       battleEffect: "BulkUp",                      damageType:  null      }, 
	"Bounce"        : { name: "Bounce",        battleEffect: "Bounce",                      damageType: "Flying"   }, 
	"Mud Shot"      : { name: "Mud Shot",      battleEffect: "DamageAndTargetSpeedDown1",   damageType: "Ground"   }, 
	"Poison Tail"   : { name: "Poison Tail",   battleEffect: "PoisonTail",                  damageType: "Poison"   }, 
	"Covet"         : { name: "Covet",         battleEffect: "StealItem",                   damageType: "Normal"   }, 
	"Volt Tackle"   : { name: "Volt Tackle",   battleEffect: "VoltTackle",                  damageType: "Electric" }, 
	"Magical Leaf"  : { name: "Magical Leaf",  battleEffect: "CannotMiss",                  damageType: "Grass"    }, 
	"Water Sport"   : { name: "Water Sport",   battleEffect: "WaterSport",                  damageType:  null      }, 
	"Calm Mind"     : { name: "Calm Mind",     battleEffect: "CalmMind",                    damageType:  null      }, 
	"Leaf Blade"    : { name: "Leaf Blade",    battleEffect: "HighCritical",                damageType: "Grass"    }, 
	"Dragon Dance"  : { name: "Dragon Dance",  battleEffect: "DragonDance",                 damageType:  null      }, 
	"Rock Blast"    : { name: "Rock Blast",    battleEffect:  null,                         damageType: "Rock"     }, 
	"Shock Wave"    : { name: "Shock Wave",    battleEffect: "CannotMiss",                  damageType: "Electric" }, 
	"Water Pulse"   : { name: "Water Pulse",   battleEffect:  null,                         damageType: "Water"    }, 
	"Doom Desire"   : { name: "Doom Desire",   battleEffect: "FutureAttack",                damageType: "Steel"    }, 
	"Psycho Boost"  : { name: "Psycho Boost",  battleEffect: "DamageAndUserSpattackDown2",  damageType: "Psychic"  }, 
	"Roost"         : { name: "Roost",         battleEffect: "Roost",                       damageType:  null      }, 
	"Gravity"       : { name: "Gravity",       battleEffect: "Gravity",                     damageType:  null      }, 
	"Miracle Eye"   : { name: "Miracle Eye",   battleEffect: "MiracleEye",                  damageType:  null      }, 
	"Wake-Up Slap"  : { name: "Wake-Up Slap",  battleEffect: "WakeUpSlap",                  damageType: "Fighting" }, 
	"Hammer Arm"    : { name: "Hammer Arm",    battleEffect: "HammerArm",                   damageType: "Fighting" }, 
	"Gyro Ball"     : { name: "Gyro Ball",     battleEffect: "GyroBall",                    damageType: "Steel"    }, 
	"Healing Wish"  : { name: "Healing Wish",  battleEffect: "HealingWish",                 damageType:  null      }, 
	"Brine"         : { name: "Brine",         battleEffect: "Brine",                       damageType: "Water"    }, 
	"Natural Gift"  : { name: "Natural Gift",  battleEffect: "NaturalGift",                 damageType: "Normal"   }, 
	"Feint"         : { name: "Feint",         battleEffect: "Feint",                       damageType: "Normal"   }, 
	"Pluck"         : { name: "Pluck",         battleEffect: "StealBerry",                  damageType: "Flying"   }, 
	"Tailwind"      : { name: "Tailwind",      battleEffect: "Tailwind",                    damageType:  null      }, 
	"Acupressure"   : { name: "Acupressure",   battleEffect: "Acupressure",                 damageType:  null      }, 
	"Metal Burst"   : { name: "Metal Burst",   battleEffect: "MetalBurst",                  damageType:  null      }, 
	"U-turn"        : { name: "U-turn",        battleEffect: "UTurn",                       damageType: "Bug"      }, 
	"Close Combat"  : { name: "Close Combat",  battleEffect: "CloseCombat",                 damageType: "Fighting" }, 
	"Payback"       : { name: "Payback",       battleEffect: "Payback",                     damageType: "Dark"     }, 
	"Assurance"     : { name: "Assurance",     battleEffect: "Assurance",                   damageType: "Dark"     }, 
	"Embargo"       : { name: "Embargo",       battleEffect: "Embargo",                     damageType:  null      }, 
	"Fling"         : { name: "Fling",         battleEffect: "Fling",                       damageType:  null      }, 
	"Psycho Shift"  : { name: "Psycho Shift",  battleEffect: "PsychoShift",                 damageType:  null      }, 
	"Trump Card"    : { name: "Trump Card",    battleEffect: "TrumpCard",                   damageType:  null      }, 
	"Heal Block"    : { name: "Heal Block",    battleEffect: "HealBlock",                   damageType:  null      }, 
	"Wring Out"     : { name: "Wring Out",     battleEffect: "DamageByTargetHealth",        damageType:  null      }, 
	"Power Trick"   : { name: "Power Trick",   battleEffect: "PowerTrick",                  damageType:  null      }, 
	"Gastro Acid"   : { name: "Gastro Acid",   battleEffect: "GastroAcid",                  damageType:  null      }, 
	"Lucky Chant"   : { name: "Lucky Chant",   battleEffect: "LuckyChant",                  damageType:  null      }, 
	"Me First"      : { name: "Me First",      battleEffect: "MeFirst",                     damageType:  null      }, 
	"Copycat"       : { name: "Copycat",       battleEffect: "Copycat",                     damageType:  null      }, 
	"Power Swap"    : { name: "Power Swap",    battleEffect: "PowerSwap",                   damageType:  null      }, 
	"Guard Swap"    : { name: "Guard Swap",    battleEffect: "GuardSwap",                   damageType:  null      }, 
	"Punishment"    : { name: "Punishment",    battleEffect: "Punishment",                  damageType:  null      }, 
	"Last Resort"   : { name: "Last Resort",   battleEffect: "LastResort",                  damageType: "Normal"   }, 
	"Worry Seed"    : { name: "Worry Seed",    battleEffect: "WorrySeed",                   damageType:  null      }, 
	"Sucker Punch"  : { name: "Sucker Punch",  battleEffect: "SuckerPunch",                 damageType: "Dark"     }, 
	"Toxic Spikes"  : { name: "Toxic Spikes",  battleEffect: "ToxicSpikes",                 damageType:  null      }, 
	"Heart Swap"    : { name: "Heart Swap",    battleEffect: "HeartSwap",                   damageType:  null      }, 
	"Aqua Ring"     : { name: "Aqua Ring",     battleEffect: "AquaRing",                    damageType:  null      }, 
	"Magnet Rise"   : { name: "Magnet Rise",   battleEffect: "MagnetRise",                  damageType:  null      }, 
	"Flare Blitz"   : { name: "Flare Blitz",   battleEffect: "FlareBlitz",                  damageType: "Fire"     }, 
	"Force Palm"    : { name: "Force Palm",    battleEffect:  null,                         damageType: "Fighting" }, 
	"Aura Sphere"   : { name: "Aura Sphere",   battleEffect: "CannotMiss",                  damageType: "Fighting" }, 
	"Rock Polish"   : { name: "Rock Polish",   battleEffect: "UserSpeedUp2",                damageType:  null      }, 
	"Poison Jab"    : { name: "Poison Jab",    battleEffect:  null,                         damageType: "Poison"   }, 
	"Dark Pulse"    : { name: "Dark Pulse",    battleEffect:  null,                         damageType: "Dark"     }, 
	"Night Slash"   : { name: "Night Slash",   battleEffect: "HighCritical",                damageType: "Dark"     }, 
	"Aqua Tail"     : { name: "Aqua Tail",     battleEffect:  null,                         damageType: "Water"    }, 
	"Seed Bomb"     : { name: "Seed Bomb",     battleEffect:  null,                         damageType: "Grass"    }, 
	"Air Slash"     : { name: "Air Slash",     battleEffect:  null,                         damageType: "Flying"   }, 
	"X-Scissor"     : { name: "X-Scissor",     battleEffect:  null,                         damageType: "Bug"      }, 
	"Bug Buzz"      : { name: "Bug Buzz",      battleEffect:  null,                         damageType: "Bug"      }, 
	"Dragon Pulse"  : { name: "Dragon Pulse",  battleEffect:  null,                         damageType: "Dragon"   }, 
	"Dragon Rush"   : { name: "Dragon Rush",   battleEffect:  null,                         damageType: "Dragon"   }, 
	"Power Gem"     : { name: "Power Gem",     battleEffect:  null,                         damageType: "Rock"     }, 
	"Drain Punch"   : { name: "Drain Punch",   battleEffect: "HpDrain",                     damageType: "Fighting" }, 
	"Vacuum Wave"   : { name: "Vacuum Wave",   battleEffect: "Priority",                    damageType: "Fighting" }, 
	"Focus Blast"   : { name: "Focus Blast",   battleEffect:  null,                         damageType: "Fighting" }, 
	"Energy Ball"   : { name: "Energy Ball",   battleEffect:  null,                         damageType: "Grass"    }, 
	"Brave Bird"    : { name: "Brave Bird",    battleEffect: "13Recoil",                    damageType: "Flying"   }, 
	"Earth Power"   : { name: "Earth Power",   battleEffect:  null,                         damageType: "Ground"   }, 
	"Switcheroo"    : { name: "Switcheroo",    battleEffect: "SwitchItems",                 damageType:  null      }, 
	"Giga Impact"   : { name: "Giga Impact",   battleEffect: "MustRecharge",                damageType: "Normal"   }, 
	"Nasty Plot"    : { name: "Nasty Plot",    battleEffect: "UserSpattackUp2",             damageType:  null      }, 
	"Bullet Punch"  : { name: "Bullet Punch",  battleEffect: "Priority",                    damageType: "Steel"    }, 
	"Avalanche"     : { name: "Avalanche",     battleEffect: "DamageRevenge",               damageType: "Ice"      }, 
	"Ice Shard"     : { name: "Ice Shard",     battleEffect: "Priority",                    damageType: "Ice"      }, 
	"Shadow Claw"   : { name: "Shadow Claw",   battleEffect: "HighCritical",                damageType: "Ghost"    }, 
	"Thunder Fang"  : { name: "Thunder Fang",  battleEffect:  null,                         damageType: "Electric" }, 
	"Ice Fang"      : { name: "Ice Fang",      battleEffect:  null,                         damageType: "Ice"      }, 
	"Fire Fang"     : { name: "Fire Fang",     battleEffect:  null,                         damageType: "Fire"     }, 
	"Shadow Sneak"  : { name: "Shadow Sneak",  battleEffect: "Priority",                    damageType: "Ghost"    }, 
	"Mud Bomb"      : { name: "Mud Bomb",      battleEffect:  null,                         damageType: "Ground"   }, 
	"Psycho Cut"    : { name: "Psycho Cut",    battleEffect: "HighCritical",                damageType: "Psychic"  }, 
	"Zen Headbutt"  : { name: "Zen Headbutt",  battleEffect:  null,                         damageType: "Psychic"  }, 
	"Mirror Shot"   : { name: "Mirror Shot",   battleEffect:  null,                         damageType: "Steel"    }, 
	"Flash Cannon"  : { name: "Flash Cannon",  battleEffect:  null,                         damageType: "Steel"    }, 
	"Rock Climb"    : { name: "Rock Climb",    battleEffect:  null,                         damageType: "Normal"   }, 
	"Defog"         : { name: "Defog",         battleEffect: "Defog",                       damageType:  null      }, 
	"Trick Room"    : { name: "Trick Room",    battleEffect: "TrickRoom",                   damageType:  null      }, 
	"Draco Meteor"  : { name: "Draco Meteor",  battleEffect: "DamageAndUserSpattackDown2",  damageType: "Dragon"   }, 
	"Discharge"     : { name: "Discharge",     battleEffect:  null,                         damageType: "Electric" }, 
	"Lava Plume"    : { name: "Lava Plume",    battleEffect:  null,                         damageType: "Fire"     }, 
	"Leaf Storm"    : { name: "Leaf Storm",    battleEffect: "DamageAndUserSpattackDown2",  damageType: "Grass"    }, 
	"Power Whip"    : { name: "Power Whip",    battleEffect:  null,                         damageType: "Grass"    }, 
	"Rock Wrecker"  : { name: "Rock Wrecker",  battleEffect: "MustRecharge",                damageType: "Rock"     }, 
	"Cross Poison"  : { name: "Cross Poison",  battleEffect: "PoisonTail",                  damageType: "Poison"   }, 
	"Gunk Shot"     : { name: "Gunk Shot",     battleEffect:  null,                         damageType: "Poison"   }, 
	"Iron Head"     : { name: "Iron Head",     battleEffect:  null,                         damageType: "Steel"    }, 
	"Magnet Bomb"   : { name: "Magnet Bomb",   battleEffect: "CannotMiss",                  damageType: "Steel"    }, 
	"Stone Edge"    : { name: "Stone Edge",    battleEffect: "HighCritical",                damageType: "Rock"     }, 
	"Captivate"     : { name: "Captivate",     battleEffect: "Captivate",                   damageType:  null      }, 
	"Stealth Rock"  : { name: "Stealth Rock",  battleEffect: "StealthRock",                 damageType:  null      }, 
	"Grass Knot"    : { name: "Grass Knot",    battleEffect: "DamageByTargetWeight",        damageType: "Grass"    }, 
	"Chatter"       : { name: "Chatter",       battleEffect:  null,                         damageType: "Flying"   }, 
	"Judgment"      : { name: "Judgment",      battleEffect: "Judgment",                    damageType: "Normal"   }, 
	"Bug Bite"      : { name: "Bug Bite",      battleEffect: "StealBerry",                  damageType: "Bug"      }, 
	"Charge Beam"   : { name: "Charge Beam",   battleEffect:  null,                         damageType: "Electric" }, 
	"Wood Hammer"   : { name: "Wood Hammer",   battleEffect: "13Recoil",                    damageType: "Grass"    }, 
	"Aqua Jet"      : { name: "Aqua Jet",      battleEffect: "Priority",                    damageType: "Water"    }, 
	"Attack Order"  : { name: "Attack Order",  battleEffect: "HighCritical",                damageType: "Bug"      }, 
	"Defend Order"  : { name: "Defend Order",  battleEffect: "BothDefenseUp1",              damageType:  null      }, 
	"Heal Order"    : { name: "Heal Order",    battleEffect: "Recover",                     damageType:  null      }, 
	"Head Smash"    : { name: "Head Smash",    battleEffect: "12Recoil",                    damageType: "Rock"     }, 
	"Double Hit"    : { name: "Double Hit",    battleEffect:  null,                         damageType: "Normal"   }, 
	"Roar of Time"  : { name: "Roar of Time",  battleEffect: "MustRecharge",                damageType: "Dragon"   }, 
	"Spacial Rend"  : { name: "Spacial Rend",  battleEffect: "HighCritical",                damageType: "Dragon"   }, 
	"Lunar Dance"   : { name: "Lunar Dance",   battleEffect: "LunarDance",                  damageType:  null      }, 
	"Crush Grip"    : { name: "Crush Grip",    battleEffect: "DamageByTargetHealth",        damageType:  null      }, 
	"Magma Storm"   : { name: "Magma Storm",   battleEffect: "Trap",                        damageType: "Fire"     }, 
	"Dark Void"     : { name: "Dark Void",     battleEffect: "InflictSleep",                damageType:  null      }, 
	"Seed Flare"    : { name: "Seed Flare",    battleEffect:  null,                         damageType: "Grass"    }, 
	"Ominous Wind"  : { name: "Ominous Wind",  battleEffect:  null,                         damageType: "Ghost"    }, 
	"Shadow Force"  : { name: "Shadow Force",  battleEffect: "ShadowForce",                 damageType: "Ghost"    }
};